### ISSUE TITLE
A question about this paper

### ISSUE THREAD

**Issue by zhanjiahui** [ZhenbangDu/Reliable_AD#3]
Thank you very much for the your wonderful work.
However, I have a question about the paper. Section 4.3 mentions the 'reference models' in both Equation (6) and Equation (8). Could you please clarify what is meant by 'reference model'? It does not seem to be illustrated in Figure 3.
Thank you again for the excellent work.

**Comment by ZhenbangDu** [comment]
Hello! Thank you very much for your interest in our work. It seems there might have been some confusion in our original text. By 'reference model', we mean a frozen original model (teacher model) used to provide guidance during training to prevent model collapse. You can obtain the 'reference model' by using copy.deepcopy(original_model). If you have any other questions, feel free to ask me!
